---
create_user: arthur
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa_REAL.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw', 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
